version: '3'

services:
  master:
    image: babbagecoinnode
    build: .
    volumes:
      - .:/babbagecoin/
    network_mode: host
    command: [ "master" ]
  miner:
    image: babbagecoinnode
    build: .
    volumes:
      - .:/babbagecoin/
    network_mode: host
    command: [ "miner" ]
    depends_on:
      - master
